name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        project: [backend, frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: ./${{ matrix.project }}/package-lock.json

      - name: Install Dependencies
        run: npm install --no-audit --no-fund
        working-directory: ./${{ matrix.project }}
        env:
          HUSKY: 0

      - name: Lint Code
        run: npm run lint
        working-directory: ./${{ matrix.project }}
        env:
          HUSKY: 0

      - name: Run Tests
        run: npm test
        working-directory: ./${{ matrix.project }}
        env:
          HUSKY: 0
